sitename: The Russian End
domain: therussianend.net
url: https://therussianend.net
baseurl: /
email: therussianend@gmail.com
twitter: https://x.com/TheRussianEnd

collections:
  entries:
    output: true
  cases:
    output: true
  years:
    output: true
  methods:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "main"
  - scope:
      path: "_entries"
    values:
      layout: "entry"
  - scope:
      path: "_cases"
    values:
      layout: "cases"
  - scope:
      path: "_years"
    values:
      layout: "years"
  - scope:
      path: "_methods"
    values:
      layout: "methods"