sitename: The Russian End
domain: therussianend.net
url: https://therussianend.net
baseurl: /
email: therussianend@gmail.com
twitter: https://x.com/TheRussianEnd

collections:
  entries:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_entries"
    values:
      layout: "entry"  